## Aplicação SmartBudget

server.servlet.context-path=/budget
server.shutdown=graceful
management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=health, info, shutdown
management.endpoint.health.show-details=always
spring.devtools.add-properties=false
spring.jpa.open-in-view=false

spring.sleuth.traceId128=true

spring.datasource.schema=budget
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.allow-remote-connections=true
spring.datasource.tomcat.test-on-borrow=true
spring.datasource.tomcat.validation-query=select 1
spring.datasource.sql-script-encoding=UTF-8
spring.jpa.properties.hibernate.show-sql=true

spring.datasource.url=jdbc:mariadb://192.168.12.107:3306/budget?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=BINARY
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.minimum-idle=3

# JWT Secret Key (use a long, random, and secure string in production)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970