-- MySQL Script generated by MySQL Workbench
-- Wed Aug  2 17:13:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema budget
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema budget
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `budget` DEFAULT CHARACTER SET utf8 ;
USE `budget` ;

-- -----------------------------------------------------
-- Table `budget`.`expense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`expense` (
  `id_expense` BINARY(16) NOT NULL,
  `planned_value` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_expense`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`transaction` (
  `id_transaction` BINARY(16) NOT NULL,
  `value_transaction` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(100) NULL,
  `transaction_date` DATE NOT NULL,
  `id_expense` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_id_expense_96897657_idx` (`id_expense` ASC) VISIBLE,
  CONSTRAINT `fk_id_expense_96897657`
    FOREIGN KEY (`id_expense`)
    REFERENCES `budget`.`expense` (`id_expense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`investment` (
  `id_investment` BINARY(16) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_investment`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`income_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`income_category` (
  `id_income_category` BINARY(16) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_income_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`income` (
  `id_income` BINARY(16) NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `id_income_category` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_income`),
  INDEX `fk_id_income_category_6878923_idx` (`id_income_category` ASC) VISIBLE,
  CONSTRAINT `fk_id_income_category_6878923`
    FOREIGN KEY (`id_income_category`)
    REFERENCES `budget`.`income_category` (`id_income_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


insert into budget.expense (id_expense, planned_value, description)
values
(UUID_TO_BIN('c96adcca-00d5-49da-9261-dcbd0156d064'), 0, 'Supermercado'),
(UUID_TO_BIN('35712e6d-48bd-4b98-aa4b-5924d71462b5'), 0, 'Entretenimento'),
(UUID_TO_BIN('c91d30f7-d16e-4ef7-bdde-69827f73c319'), 0, 'Transporte'),
(UUID_TO_BIN('d117c5b6-3af7-4f75-96b9-ce64386d48c1'), 0, 'Saúde'),
(UUID_TO_BIN('5e6c1734-9e11-4eae-ba77-8fb75fce559c'), 0, 'Fastfood'),
(UUID_TO_BIN('6a70131a-ba75-4031-b47b-bb0ea34dd9ff'), 0, 'Contas utilidade pública'),
(UUID_TO_BIN('3e37b6f9-22e5-4951-a889-38cba1f293d7'), 0, 'Programa em casal'),
(UUID_TO_BIN('7c6c5e40-7e1f-4b03-8ef3-594a23e2254e'), 0, 'Programa em amigos'),
(UUID_TO_BIN('3c9d63e6-d94d-4e46-b72a-0ec4fec5d68f'), 0, 'Outros');