-- MySQL Script generated by MySQL Workbench
-- Wed Aug  2 17:13:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema budget
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema budget
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `budget` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `budget` ;

-- -----------------------------------------------------
-- Table `budget`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`category` (
  `id_category` BINARY(16) NOT NULL,
  `parent_id_category` BINARY(16) NULL,
  `planned_value` DECIMAL(10,2) NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`transaction` (
  `id_transaction` BINARY(16) NOT NULL,
  `value_transaction` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(100) NULL,
  `transaction_date` DATE NOT NULL,
  `id_category` BINARY(16) NOT NULL,
  `installment_number` INT DEFAULT NULL,
  `installment_total` INT DEFAULT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_id_category_96897657_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `fk_id_category_96897657`
    FOREIGN KEY (`id_category`)
    REFERENCES `budget`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `budget`.`investment_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`investment_type` (
  `id_investment_type` BINARY(16) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_investment_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`location` (
  `id_location` BINARY(16) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `budget`.`investment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`investment` (
  `id_investment` BINARY(16) NOT NULL,
  `id_portfolio` BINARY(16) NOT NULL,
  `id_investment_type` BINARY(16) NOT NULL,
  `id_location` BINARY(16) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL,
  `month_revenue` DECIMAL(10,2) NOT NULL,
  `last_update_date` DATE NOT NULL,
  PRIMARY KEY (`id_investment`),
  INDEX `fk_investment_type_idx` (`id_investment_type` ASC) VISIBLE,
  INDEX `fk_location_idx` (`id_location` ASC) VISIBLE,
  INDEX `idx_id_portfolio` (`id_portfolio` ASC) VISIBLE,
  CONSTRAINT `fk_investment_investment_type`
    FOREIGN KEY (`id_investment_type`)
    REFERENCES `budget`.`investment_type` (`id_investment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investment_location`
    FOREIGN KEY (`id_location`)
    REFERENCES `budget`.`location` (`id_location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`income_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`income_category` (
  `id_income_category` BINARY(16) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_income_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `budget`.`income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`income` (
  `id_income` BINARY(16) NOT NULL,
  `value` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `income_date` DATE NOT NULL,
  `id_income_category` BINARY(16) NOT NULL,
  PRIMARY KEY (`id_income`),
  INDEX `fk_id_income_category_6878923_idx` (`id_income_category` ASC) VISIBLE,
  CONSTRAINT `fk_id_income_category_6878923`
    FOREIGN KEY (`id_income_category`)
    REFERENCES `budget`.`income_category` (`id_income_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `budget`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `budget`.`users` (
  `id` BINARY(16) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_r43af9ap4edm43mmtq01oddj6` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELIMITER //

DROP FUNCTION IF EXISTS UUID_TO_BIN_SWAP //

CREATE FUNCTION UUID_TO_BIN(uuid_str CHAR(36))
RETURNS BINARY(16)
DETERMINISTIC
BEGIN
    RETURN UNHEX(CONCAT(
        SUBSTRING(uuid_str, 15, 4),   -- time_mid
        SUBSTRING(uuid_str, 10, 4),   -- time_low
        SUBSTRING(uuid_str,  1, 8),   -- time_hi + version
        SUBSTRING(uuid_str, 20, 4),
        SUBSTRING(uuid_str, 25, 12)
    ));
END //

DROP FUNCTION IF EXISTS BIN_TO_UUID //

CREATE FUNCTION BIN_TO_UUID(bin_uuid BINARY(16))
RETURNS CHAR(36)
DETERMINISTIC
BEGIN
    SET @hex = HEX(bin_uuid);
    RETURN LOWER(CONCAT(
        SUBSTRING(@hex,  1,  8), '-',
        SUBSTRING(@hex,  9,  4), '-',
        SUBSTRING(@hex, 13,  4), '-',
        SUBSTRING(@hex, 17,  4), '-',
        SUBSTRING(@hex, 21, 12)
    ));
END //

DELIMITER ;